Update portalguide.md
nih-cfde/published-documentation pull request #284
Opened 2021-10-28 21:02 UTC by fridayek

Updated with Portal changes.

2021-10-28 21:09 UTC, ACharbonneau commented
@raynamharris Could you review this please? It's updated docs for the new UI you're looking at.

2021-10-29 16:47 UTC, raynamharris requested changes
This is great! I was able to follow along, and it seems that all the changes point the reader to the appropriately named tabs and such that have been changed in the latest revision. I only found one typo in a URL path that needs to be corrected.

2021-10-29 16:47 UTC, raynamharris commented on docs/about/portalguide.md
> +The CFDE website includes two modules to ensure the specific goals are met and users can find data—the [portal](https://app.nih-cfde.org/) and the [dashboard](https://https://app.nih-cfde.org/udashbo
the new path has `https://` repeated twice, so it is invalid. As a side note, https://app.nih-cfde.org/dashboard.html redirects to the appropriate https://app.nih-cfde.org/udashboard.html so that's good

2021-10-29 17:16 UTC, raynamharris commented
As I was reviewing this PR, I thought, I really should've read this before I started clicking buttons and blinding exploring the data. Yes, this document is easily accessed from the "User Help" drop-down menu, but I didn't really notice that at first. Thus, I suggested providing a link to the User Guide in dib-lab/cfde-helpdesk#8

2021-11-02 14:24 UTC, raynamharris commented
@ACharbonneau I'm happy to merge this and then fix the hyperlink in a separate PR if that helps

2021-11-03 21:36 UTC, ACharbonneau commented
@raynamharris could you merge and do the hyperlink in a new one? Since the new portal is live it would be good to have the right docs linked :)

2021-11-03 21:39 UTC, ACharbonneau commented
could you figure out the other two PRs as well? It looks like they're supposed to be adding images to this one

2021-11-05 13:38 UTC, raynamharris approved these changes

2021-11-05 13:42 UTC, merged